apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-poc
  labels:
    {{- include "otel-poc.labels" . | nindent 4 }}
  {{- if eq .Values.env "gke" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount | quote }}
  {{- end }}
