apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ include "otel-stack.namespace" . }}
  labels:
    {{- include "otel-stack.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount | quote }}
