{{- if .Values.deps.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "otel-poc.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        {{- include "otel-poc.labels" . | nindent 8 }}
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - { name: pg, containerPort: 5432 }
          env:
            - { name: POSTGRES_USER, value: "postgres" }
            - { name: POSTGRES_PASSWORD, value: "postgres" }
            - { name: POSTGRES_DB, value: "{{ include "otel-poc.pgdb" . }}" }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "otel-poc.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - { name: pg, port: 5432, targetPort: 5432 }
{{- end }}
